version: '3.8'

services:
  otel-collector:
    build: .
    container_name: otel-collector
    volumes:
      - ./otel-collector-config.yaml:/etc/otel/config.yaml  # Modifique o destino para /etc/otel/config.yaml
    ports:
      - "4317:4317"  # OTLP gRPC
      - "4318:4318"  # OTLP HTTP
      - "55679:55679"  # ZPages (debug)
