receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  # Usando o exportador debug em vez de logging
  debug:
    level: debug  # Ajuste o nível conforme necessário
  logging:
    level: debug

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, logging]
