receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

exporters:
  otlp:
    endpoint: http://84.247.143.19:9090


service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [otlp]
