receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  prometheus:
    endpoint: "http://84.247.143.19:9090/"
  debug: {}  # Substituindo 'logging' por 'debug'

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]  # Exportando logs para o debug exporter
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]  # Exportando métricas para o Prometheus
