receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  prometheus:
    endpoint: "http://84.247.143.19:9090/"

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
