receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:

exporters:
  otlp/metrics:
    endpoint: https://prometheus.ragde.app:9090
    tls:
      insecure: true
      insecure_skip_verify: false

  otlp/traces:
    endpoint: http://tempo:4317
    tls:
      insecure: true

extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/metrics]

    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/traces]
