version: '3.8'

services:
  otel-collector:
    build: .
    container_name: otel-collector
    volumes:
      - ./otel-collector-config.yaml:/etc/otel/config.yaml
    ports:
      - "4317:4317"  # OTLP gRPC
      - "4318:4318"  # OTLP HTTP
      - "55679:55679"  # ZPages (debug)

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    volumes:
      - ./tempo.yml:/etc/tempo.yml
      - ./tempo-data:/var/tempo/traces
    command: [ "-config.file=/etc/tempo.yml" ]
    ports:
      - "3200:3200" # API Tempo
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - ./grafana:/var/lib/grafana
